[workspace]
resolver = "2"
members = [
    "./guessing_game",
    "./loops",
    "./named_loops",
    "./overflow-handling",
    "./shadowing",
    "./array_loops",
    "./ownership",
    "./return_ownership",
    "./structs",
    "./structs_rectangle"
]

